apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zwi0jx9ay-nodejs 
  janus-idp.io/tekton: zwi0jx9ay-nodejs
  backstage.io/kubernetes-id: zwi0jx9ay-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zwi0jx9ay-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml