apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zwi0jx9ay-nodejs
  janus-idp.io/tekton: zwi0jx9ay-nodejs
  backstage.io/kubernetes-id: zwi0jx9ay-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zwi0jx9ay-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
