apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zwi0jx9ay-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zwi0jx9ay-nodejs 
  name: zwi0jx9ay-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zwi0jx9ay-nodejs 
